# Generated by Django 4.0 on 2022-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_logo', verbose_name='profile logo'),
        ),
    ]
